import React from 'react';
import type { Metadata } from 'next';
import CustomSessionProvider from '@/app/context/CustomSessionProvider';
import '@/app/styles/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="ko">
      <body>
        <CustomSessionProvider>{children}</CustomSessionProvider>
      </body>
    </html>
  );
}
